export default {
	CUSTOMER: {
		GET_CUSTOMER_STARTED: 'GET_CUSTOMER_STARTED',
		GET_CUSTOMER_SUCCESS: 'GET_CUSTOMER_SUCCESS',
		GET_CUSTOMER_FAILED: 'GET_CUSTOMER_FAILED',
		SET_ACCOUNT_STARTED: 'SET_ACCOUNT_SUCCESS',
		SET_ACCOUNT_SUCCESS: 'SET_ACCOUNT_STARTED',
		SET_ACCOUNT_FAILED: 'SET_ACCOUNT_FAILED'
	}
}